--- #YAML:1.0
name:                ExtUtils-MakeMaker
version:             6.32
abstract:            Create a module Makefile
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    DirHandle:                     0
    File::Basename:                0
    File::Spec:                    0.8
    Pod::Man:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Michael G Schwern <schwern@pobox.com>
no_index:
    dir:
        - inc
