--- #YAML:1.0
name:                ExtUtils-MakeMaker
version:             6.30_04
abstract:            Create a module Makefile
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.30_04
author:              Michael G Schwern <schwern@pobox.com>
distribution_type:   module
requires:     
    DirHandle:                     0
    File::Basename:                0
    File::Spec:                    0.8
    Pod::Man:                      0
meta-spec:
    url: http://module-build.sourceforge.net/META-spec-new.html
    version: 1.1
no_index:
    dir:
        - inc
