--- #YAML:1.0
name:                ExtUtils-MakeMaker
version:             6.43_01
abstract:            Create a module Makefile
license:             perl
author:              
    - Michael G Schwern <schwern@pobox.com>
generated_by:        ExtUtils::MakeMaker version 6.43_01
distribution_type:   module
requires:     
    DirHandle:                     0
    File::Basename:                0
    File::Spec:                    0.8
    Pod::Man:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
no_index:
    directory:
        - inc
    package:
        - DynaLoader
resources:
    license:     http://dev.perl.org/licenses/
    homepage:    http://makemaker.org
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=ExtUtils-MakeMaker
    repository:  http://svn.schwern.org/svn/CPAN/ExtUtils-MakeMaker
    MailingList: makemaker@perl.org
