#!/usr/local/bin/perl

# $Id: mm_dummy_exe,v 1.1 1996/12/20 14:37:24 k Exp $
my $version = substr q$Revision: 1.1 $, 10;

BEGIN {require 5.000;}

__END__

=head1 NAME

mm_dummy_exe - dummy program, does nothing

=head1 SYNOPSIS

mm_dummy_exe

=head1 DESCRIPTION

The only purpose of this dummy program is to test MakeMaker (perl
distribution), if it installs o.k.

=head1 BUGS

No features, no bugs.

=head1 AUTHOR

Andreas König

=cut

